//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyAsio.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyAsio.Lang.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An ASIO/WASAPI Exclusive middleware for osu! players. Exploring the limits of low-latency audio. 的本地化字符串。
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag the sphere to explore the list 的本地化字符串。
        /// </summary>
        internal static string About_DragToExplore {
            get {
                return ResourceManager.GetString("About_DragToExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore More 的本地化字符串。
        /// </summary>
        internal static string About_ExploreMore {
            get {
                return ResourceManager.GetString("About_ExploreMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special Thanks 的本地化字符串。
        /// </summary>
        internal static string About_SpecialThanks {
            get {
                return ResourceManager.GetString("About_SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks to all supporters of KeyASIO, you make this project better 的本地化字符串。
        /// </summary>
        internal static string About_SpecialThanksDescription {
            get {
                return ResourceManager.GetString("About_SpecialThanksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeyASIO Audio Backend 的本地化字符串。
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit 的本地化字符串。
        /// </summary>
        internal static string About_Visit {
            get {
                return ResourceManager.GetString("About_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeyASIO 的本地化字符串。
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backend Selection 的本地化字符串。
        /// </summary>
        internal static string Audio_BackendSelection {
            get {
                return ResourceManager.GetString("Audio_BackendSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer 的本地化字符串。
        /// </summary>
        internal static string Audio_Buffer {
            get {
                return ResourceManager.GetString("Audio_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Device 的本地化字符串。
        /// </summary>
        internal static string Audio_ClearDevice {
            get {
                return ResourceManager.GetString("Audio_ClearDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Device 的本地化字符串。
        /// </summary>
        internal static string Audio_Device {
            get {
                return ResourceManager.GetString("Audio_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Panel 的本地化字符串。
        /// </summary>
        internal static string Audio_DriverPanel {
            get {
                return ResourceManager.GetString("Audio_DriverPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Type 的本地化字符串。
        /// </summary>
        internal static string Audio_DriverType {
            get {
                return ResourceManager.GetString("Audio_DriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine Status 的本地化字符串。
        /// </summary>
        internal static string Audio_EngineStatus {
            get {
                return ResourceManager.GetString("Audio_EngineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclusive 的本地化字符串。
        /// </summary>
        internal static string Audio_Exclusive {
            get {
                return ResourceManager.GetString("Audio_Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclusive Mode 的本地化字符串。
        /// </summary>
        internal static string Audio_ExclusiveMode {
            get {
                return ResourceManager.GetString("Audio_ExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Buffer Size 的本地化字符串。
        /// </summary>
        internal static string Audio_ForceBufferSize {
            get {
                return ResourceManager.GetString("Audio_ForceBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latency 的本地化字符串。
        /// </summary>
        internal static string Audio_Latency {
            get {
                return ResourceManager.GetString("Audio_Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latency &amp; Buffer 的本地化字符串。
        /// </summary>
        internal static string Audio_LatencyAndBuffer {
            get {
                return ResourceManager.GetString("Audio_LatencyAndBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Limiter 的本地化字符串。
        /// </summary>
        internal static string Audio_Limiter {
            get {
                return ResourceManager.GetString("Audio_Limiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevents clipping when hitsounds stack. &apos;Polynomial&apos; mode is recommended; disable for raw audio. Note: &apos;Master&apos; mode increases CPU usage. 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterDescription {
            get {
                return ResourceManager.GetString("Audio_LimiterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard (Clipping) 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Hard {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master (Lookahead) 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Master {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Off {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polynomial (Zero‑latency) 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Polynomial {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Polynomial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quadratic (Lightweight) 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Quadratic {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Quadratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soft (Saturation) 的本地化字符串。
        /// </summary>
        internal static string Audio_LimiterType_Soft {
            get {
                return ResourceManager.GetString("Audio_LimiterType_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No device selected.  的本地化字符串。
        /// </summary>
        internal static string Audio_NoDeviceSelected {
            get {
                return ResourceManager.GetString("Audio_NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Device 的本地化字符串。
        /// </summary>
        internal static string Audio_OutputDevice {
            get {
                return ResourceManager.GetString("Audio_OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Processing 的本地化字符串。
        /// </summary>
        internal static string Audio_Processing {
            get {
                return ResourceManager.GetString("Audio_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Device 的本地化字符串。
        /// </summary>
        internal static string Audio_ReloadDevice {
            get {
                return ResourceManager.GetString("Audio_ReloadDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample Rate 的本地化字符串。
        /// </summary>
        internal static string Audio_SampleRate {
            get {
                return ResourceManager.GetString("Audio_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Latency 的本地化字符串。
        /// </summary>
        internal static string Audio_TargetLatency {
            get {
                return ResourceManager.GetString("Audio_TargetLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binaural Mix (Mono) 的本地化字符串。
        /// </summary>
        internal static string BalanceMode_BinauralMix {
            get {
                return ResourceManager.GetString("BalanceMode_BinauralMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant Power (Standard) 的本地化字符串。
        /// </summary>
        internal static string BalanceMode_ConstantPower {
            get {
                return ResourceManager.GetString("BalanceMode_ConstantPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cross Mix (Spatial) 的本地化字符串。
        /// </summary>
        internal static string BalanceMode_CrossMix {
            get {
                return ResourceManager.GetString("BalanceMode_CrossMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mid-Side (Professional) 的本地化字符串。
        /// </summary>
        internal static string BalanceMode_MidSide {
            get {
                return ResourceManager.GetString("BalanceMode_MidSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard 的本地化字符串。
        /// </summary>
        internal static string Common_Discard {
            get {
                return ResourceManager.GetString("Common_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Common_Done {
            get {
                return ResourceManager.GetString("Common_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to settings 的本地化字符串。
        /// </summary>
        internal static string Common_GoToSettings {
            get {
                return ResourceManager.GetString("Common_GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Later 的本地化字符串。
        /// </summary>
        internal static string Common_Later {
            get {
                return ResourceManager.GetString("Common_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string Common_Off {
            get {
                return ResourceManager.GetString("Common_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string Common_On {
            get {
                return ResourceManager.GetString("Common_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beatmap 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Beatmap {
            get {
                return ResourceManager.GetString("Dashboard_Beatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Bindings 的本地化字符串。
        /// </summary>
        internal static string Dashboard_EditBindings {
            get {
                return ResourceManager.GetString("Dashboard_EditBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keys 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Keys {
            get {
                return ResourceManager.GetString("Dashboard_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Time 的本地化字符串。
        /// </summary>
        internal static string Dashboard_PlayTime {
            get {
                return ResourceManager.GetString("Dashboard_PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Status {
            get {
                return ResourceManager.GetString("Dashboard_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync both hitsounds and music 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Sync_All_Tooltip {
            get {
                return ResourceManager.GetString("Dashboard_Sync_All_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFX 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Sync_SFX {
            get {
                return ResourceManager.GetString("Dashboard_Sync_SFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync hitsounds only 的本地化字符串。
        /// </summary>
        internal static string Dashboard_Sync_SFX_Tooltip {
            get {
                return ResourceManager.GetString("Dashboard_Sync_SFX_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Status 的本地化字符串。
        /// </summary>
        internal static string Dashboard_SyncStatus {
            get {
                return ResourceManager.GetString("Dashboard_SyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current OS version {0} is not supported. Requires Windows Vista or later. 的本地化字符串。
        /// </summary>
        internal static string Error_OSNotSupported {
            get {
                return ResourceManager.GetString("Error_OSNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind Left Mouse Button 的本地化字符串。
        /// </summary>
        internal static string KeyBinding_BindLeftMouse {
            get {
                return ResourceManager.GetString("KeyBinding_BindLeftMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to bind Left Mouse Button 的本地化字符串。
        /// </summary>
        internal static string KeyBinding_BindLeftMouseTooltip {
            get {
                return ResourceManager.GetString("KeyBinding_BindLeftMouseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Bindings 的本地化字符串。
        /// </summary>
        internal static string KeyBinding_EditBindings {
            get {
                return ResourceManager.GetString("KeyBinding_EditBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press any key to bind... 的本地化字符串。
        /// </summary>
        internal static string KeyBinding_Message {
            get {
                return ResourceManager.GetString("KeyBinding_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to Update 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ClickToUpdate {
            get {
                return ResourceManager.GetString("MainWindow_ClickToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Initialization Failed 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DeviceInitFailed_Title {
            get {
                return ResourceManager.GetString("MainWindow_DeviceInitFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send logs and errors to developer?
        ///You can change option later. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ErrorReporting_Content {
            get {
                return ResourceManager.GetString("MainWindow_ErrorReporting_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Error Reporting 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ErrorReporting_Title {
            get {
                return ResourceManager.GetString("MainWindow_ErrorReporting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to load skins from osu! folder? 的本地化字符串。
        /// </summary>
        internal static string MainWindow_LoadSkins_Content {
            get {
                return ResourceManager.GetString("MainWindow_LoadSkins_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Skins 的本地化字符串。
        /// </summary>
        internal static string MainWindow_LoadSkins_Title {
            get {
                return ResourceManager.GetString("MainWindow_LoadSkins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update {0} is Now Available. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_UpdateAvailable_Content {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        internal static string MainWindow_UpdateAvailable_Title {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest version. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_UpdateLatest_Content {
            get {
                return ResourceManager.GetString("MainWindow_UpdateLatest_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Updating_Title {
            get {
                return ResourceManager.GetString("MainWindow_Updating_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes require application to take effect 的本地化字符串。
        /// </summary>
        internal static string Message_RestartRequired {
            get {
                return ResourceManager.GetString("Message_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Engine 的本地化字符串。
        /// </summary>
        internal static string Page_AudioEngine {
            get {
                return ResourceManager.GetString("Page_AudioEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        internal static string Page_Dashboard {
            get {
                return ResourceManager.GetString("Page_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Page_Settings {
            get {
                return ResourceManager.GetString("Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Mode 的本地化字符串。
        /// </summary>
        internal static string Page_SyncMode {
            get {
                return ResourceManager.GetString("Page_SyncMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unavailable 的本地化字符串。
        /// </summary>
        internal static string Plugin_Corrupted {
            get {
                return ResourceManager.GetString("Plugin_Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme 的本地化字符串。
        /// </summary>
        internal static string Preset_Extreme {
            get {
                return ResourceManager.GetString("Preset_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximizes performance output, suitable for professional needs or high-performance scenarios. 的本地化字符串。
        /// </summary>
        internal static string Preset_ExtremeDescription {
            get {
                return ResourceManager.GetString("Preset_ExtremeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        internal static string Preset_Fast {
            get {
                return ResourceManager.GetString("Preset_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimizes resource usage, suitable for low-end devices or basic needs. 的本地化字符串。
        /// </summary>
        internal static string Preset_FastDescription {
            get {
                return ResourceManager.GetString("Preset_FastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a suitable mode based on your device performance and usage requirements. 的本地化字符串。
        /// </summary>
        internal static string Preset_SelectionDescription {
            get {
                return ResourceManager.GetString("Preset_SelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Preset Mode 的本地化字符串。
        /// </summary>
        internal static string Preset_SelectionTitle {
            get {
                return ResourceManager.GetString("Preset_SelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string Preset_Standard {
            get {
                return ResourceManager.GetString("Preset_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides balanced performance and resource usage, suitable for most general use cases. 的本地化字符串。
        /// </summary>
        internal static string Preset_StandardDescription {
            get {
                return ResourceManager.GetString("Preset_StandardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Multiple Instances 的本地化字符串。
        /// </summary>
        internal static string Settings_AllowMultipleInstances {
            get {
                return ResourceManager.GetString("Settings_AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Apply {
            get {
                return ResourceManager.GetString("Settings_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        internal static string Settings_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2022-2026 Milkitic (aka. yf_bmp). 的本地化字符串。
        /// </summary>
        internal static string Settings_CopyrightLine {
            get {
                return ResourceManager.GetString("Settings_CopyrightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Console 的本地化字符串。
        /// </summary>
        internal static string Settings_DebugConsole {
            get {
                return ResourceManager.GetString("Settings_DebugConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable AVX-512 的本地化字符串。
        /// </summary>
        internal static string Settings_EnableAvx512 {
            get {
                return ResourceManager.GetString("Settings_EnableAvx512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        internal static string Settings_Environment {
            get {
                return ResourceManager.GetString("Settings_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Reporting 的本地化字符串。
        /// </summary>
        internal static string Settings_ErrorReporting {
            get {
                return ResourceManager.GetString("Settings_ErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended Volume 的本地化字符串。
        /// </summary>
        internal static string Settings_ExtendedVolume {
            get {
                return ResourceManager.GetString("Settings_ExtendedVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow volume up to 150% 的本地化字符串。
        /// </summary>
        internal static string Settings_ExtendedVolumeDescription {
            get {
                return ResourceManager.GetString("Settings_ExtendedVolumeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        internal static string Settings_FollowSystem {
            get {
                return ResourceManager.GetString("Settings_FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input &amp; Performance 的本地化字符串。
        /// </summary>
        internal static string Settings_InputAndPerformance {
            get {
                return ResourceManager.GetString("Settings_InputAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables syncing; responds only to raw key presses. Intended for testing purposes. 的本地化字符串。
        /// </summary>
        internal static string Settings_LegacyModeDescription {
            get {
                return ResourceManager.GetString("Settings_LegacyModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legacy Mode (Key Only) 的本地化字符串。
        /// </summary>
        internal static string Settings_LegacyModeKeyOnly {
            get {
                return ResourceManager.GetString("Settings_LegacyModeKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licensed under MPL-2.0 的本地化字符串。
        /// </summary>
        internal static string Settings_LicensedUnderMpl {
            get {
                return ResourceManager.GetString("Settings_LicensedUnderMpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No updates available. 的本地化字符串。
        /// </summary>
        internal static string Settings_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Settings_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 osu! Folder Path 的本地化字符串。
        /// </summary>
        internal static string Settings_OsuFolderPath {
            get {
                return ResourceManager.GetString("Settings_OsuFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance Boost 的本地化字符串。
        /// </summary>
        internal static string Settings_PerformanceBoost {
            get {
                return ResourceManager.GetString("Settings_PerformanceBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset Mode 的本地化字符串。
        /// </summary>
        internal static string Settings_PresetMode {
            get {
                return ResourceManager.GetString("Settings_PresetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickly apply preset configurations to suit different usage scenarios. 的本地化字符串。
        /// </summary>
        internal static string Settings_PresetModeDescription {
            get {
                return ResourceManager.GetString("Settings_PresetModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw Input 的本地化字符串。
        /// </summary>
        internal static string Settings_RawInput {
            get {
                return ResourceManager.GetString("Settings_RawInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses low-latency key hooks when disabled 的本地化字符串。
        /// </summary>
        internal static string Settings_RawInputDescription {
            get {
                return ResourceManager.GetString("Settings_RawInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select osu! Folder 的本地化字符串。
        /// </summary>
        internal static string Settings_SelectOsuFolder_Title {
            get {
                return ResourceManager.GetString("Settings_SelectOsuFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update available: v 的本地化字符串。
        /// </summary>
        internal static string Settings_UpdateAvailablePrefix {
            get {
                return ResourceManager.GetString("Settings_UpdateAvailablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        internal static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        internal static string Sync_AdvancedSettings {
            get {
                return ResourceManager.GetString("Sync_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Field 的本地化字符串。
        /// </summary>
        internal static string Sync_AudioField {
            get {
                return ResourceManager.GetString("Sync_AudioField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Filters 的本地化字符串。
        /// </summary>
        internal static string Sync_AudioFilters {
            get {
                return ResourceManager.GetString("Sync_AudioFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Load Skins from osu! 的本地化字符串。
        /// </summary>
        internal static string Sync_AutoLoadSkins {
            get {
                return ResourceManager.GetString("Sync_AutoLoadSkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance Mode 的本地化字符串。
        /// </summary>
        internal static string Sync_BalanceMode {
            get {
                return ResourceManager.GetString("Sync_BalanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Combo Break 的本地化字符串。
        /// </summary>
        internal static string Sync_DisableComboBreak {
            get {
                return ResourceManager.GetString("Sync_DisableComboBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Map Hitsounds 的本地化字符串。
        /// </summary>
        internal static string Sync_DisableMapHitsounds {
            get {
                return ResourceManager.GetString("Sync_DisableMapHitsounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Slider Ticks 的本地化字符串。
        /// </summary>
        internal static string Sync_DisableSliderTicks {
            get {
                return ResourceManager.GetString("Sync_DisableSliderTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Storyboard 的本地化字符串。
        /// </summary>
        internal static string Sync_DisableStoryboard {
            get {
                return ResourceManager.GetString("Sync_DisableStoryboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Nightcore Beats 的本地化字符串。
        /// </summary>
        internal static string Sync_ForceNightcore {
            get {
                return ResourceManager.GetString("Sync_ForceNightcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Scan Interval (ms) 的本地化字符串。
        /// </summary>
        internal static string Sync_GeneralScanInterval {
            get {
                return ResourceManager.GetString("Sync_GeneralScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lower values update generic fields more promptly. Increase to reduce CPU usage. 的本地化字符串。
        /// </summary>
        internal static string Sync_GeneralScanIntervalDescription {
            get {
                return ResourceManager.GetString("Sync_GeneralScanIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Volume Changes 的本地化字符串。
        /// </summary>
        internal static string Sync_IgnoreVolumeChanges {
            get {
                return ResourceManager.GetString("Sync_IgnoreVolumeChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Control 的本地化字符串。
        /// </summary>
        internal static string Sync_MusicControl {
            get {
                return ResourceManager.GetString("Sync_MusicControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Skin 的本地化字符串。
        /// </summary>
        internal static string Sync_SelectedSkin {
            get {
                return ResourceManager.GetString("Sync_SelectedSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assets loaded from your local installation.  的本地化字符串。
        /// </summary>
        internal static string Sync_SkinDescription {
            get {
                return ResourceManager.GetString("Sync_SkinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skin Resources 的本地化字符串。
        /// </summary>
        internal static string Sync_SkinResources {
            get {
                return ResourceManager.GetString("Sync_SkinResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slider Tail Behavior 的本地化字符串。
        /// </summary>
        internal static string Sync_SliderTailBehavior {
            get {
                return ResourceManager.GetString("Sync_SliderTailBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stereo Width 的本地化字符串。
        /// </summary>
        internal static string Sync_StereoWidth {
            get {
                return ResourceManager.GetString("Sync_StereoWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing Scan Interval (ms) 的本地化字符串。
        /// </summary>
        internal static string Sync_TimingScanInterval {
            get {
                return ResourceManager.GetString("Sync_TimingScanInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lower values update timing fields more promptly. Increase if audio cutting occurs. 的本地化字符串。
        /// </summary>
        internal static string Sync_TimingScanIntervalDescription {
            get {
                return ResourceManager.GetString("Sync_TimingScanIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Narrow 的本地化字符串。
        /// </summary>
        internal static string Sync_WidthNarrow {
            get {
                return ResourceManager.GetString("Sync_WidthNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string Sync_WidthNormal {
            get {
                return ResourceManager.GetString("Sync_WidthNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wide 的本地化字符串。
        /// </summary>
        internal static string Sync_WidthWide {
            get {
                return ResourceManager.GetString("Sync_WidthWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open ASIO Options 的本地化字符串。
        /// </summary>
        internal static string TrayIcon_OpenAsioPanel {
            get {
                return ResourceManager.GetString("TrayIcon_OpenAsioPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Dashboard 的本地化字符串。
        /// </summary>
        internal static string TrayIcon_OpenDashboard {
            get {
                return ResourceManager.GetString("TrayIcon_OpenDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effect 的本地化字符串。
        /// </summary>
        internal static string Volume_Effect {
            get {
                return ResourceManager.GetString("Volume_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master 的本地化字符串。
        /// </summary>
        internal static string Volume_Master {
            get {
                return ResourceManager.GetString("Volume_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        internal static string Volume_Music {
            get {
                return ResourceManager.GetString("Volume_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Control 的本地化字符串。
        /// </summary>
        internal static string Volume_Title {
            get {
                return ResourceManager.GetString("Volume_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Device 的本地化字符串。
        /// </summary>
        internal static string Wizard_Config_Device {
            get {
                return ResourceManager.GetString("Wizard_Config_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Type 的本地化字符串。
        /// </summary>
        internal static string Wizard_Config_Driver {
            get {
                return ResourceManager.GetString("Wizard_Config_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Configuration 的本地化字符串。
        /// </summary>
        internal static string Wizard_Config_Title {
            get {
                return ResourceManager.GetString("Wizard_Config_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string Wizard_Finish {
            get {
                return ResourceManager.GetString("Wizard_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Mix (Multi-Output) 的本地化字符串。
        /// </summary>
        internal static string Wizard_Mode_Hardware {
            get {
                return ResourceManager.GetString("Wizard_Mode_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I have a dedicated sound card or mixer. I can route osu! and KeyASIO to different outputs. 的本地化字符串。
        /// </summary>
        internal static string Wizard_Mode_Hardware_Desc {
            get {
                return ResourceManager.GetString("Wizard_Mode_Hardware_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Mix (ProMix) 的本地化字符串。
        /// </summary>
        internal static string Wizard_Mode_Software {
            get {
                return ResourceManager.GetString("Wizard_Mode_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I use standard headphones/speakers. Let KeyASIO handle the mixing. 的本地化字符串。
        /// </summary>
        internal static string Wizard_Mode_Software_Desc {
            get {
                return ResourceManager.GetString("Wizard_Mode_Software_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Audio Mode 的本地化字符串。
        /// </summary>
        internal static string Wizard_Mode_Title {
            get {
                return ResourceManager.GetString("Wizard_Mode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Wizard_Next {
            get {
                return ResourceManager.GetString("Wizard_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string Wizard_Previous {
            get {
                return ResourceManager.GetString("Wizard_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates automatically 的本地化字符串。
        /// </summary>
        internal static string Wizard_Privacy_CheckUpdates {
            get {
                return ResourceManager.GetString("Wizard_Privacy_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send anonymous crash reports 的本地化字符串。
        /// </summary>
        internal static string Wizard_Privacy_CrashReport {
            get {
                return ResourceManager.GetString("Wizard_Privacy_CrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy &amp; Updates 的本地化字符串。
        /// </summary>
        internal static string Wizard_Privacy_Title {
            get {
                return ResourceManager.GetString("Wizard_Privacy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip 的本地化字符串。
        /// </summary>
        internal static string Wizard_Skip {
            get {
                return ResourceManager.GetString("Wizard_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Setup 的本地化字符串。
        /// </summary>
        internal static string Wizard_Start {
            get {
                return ResourceManager.GetString("Wizard_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Key Sound 的本地化字符串。
        /// </summary>
        internal static string Wizard_Test_KeySound {
            get {
                return ResourceManager.GetString("Wizard_Test_KeySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Music 的本地化字符串。
        /// </summary>
        internal static string Wizard_Test_Music {
            get {
                return ResourceManager.GetString("Wizard_Test_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Test 的本地化字符串。
        /// </summary>
        internal static string Wizard_Test_Title {
            get {
                return ResourceManager.GetString("Wizard_Test_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setup Wizard 的本地化字符串。
        /// </summary>
        internal static string Wizard_Title {
            get {
                return ResourceManager.GetString("Wizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Driver Detected 的本地化字符串。
        /// </summary>
        internal static string Wizard_VirtualDriver_Detected {
            get {
                return ResourceManager.GetString("Wizard_VirtualDriver_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Virtual Driver 的本地化字符串。
        /// </summary>
        internal static string Wizard_VirtualDriver_Install {
            get {
                return ResourceManager.GetString("Wizard_VirtualDriver_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extreme Low Latency
        ///(ASIO / WASAPI Exclusive) 的本地化字符串。
        /// </summary>
        internal static string Wizard_Welcome_Feature1 {
            get {
                return ResourceManager.GetString("Wizard_Welcome_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Sync
        ///(osu! Data Sync) 的本地化字符串。
        /// </summary>
        internal static string Wizard_Welcome_Feature2 {
            get {
                return ResourceManager.GetString("Wizard_Welcome_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Mixing
        ///(Personalized DSP Processing) 的本地化字符串。
        /// </summary>
        internal static string Wizard_Welcome_Feature3 {
            get {
                return ResourceManager.GetString("Wizard_Welcome_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An ASIO/WASAPI Exclusive middleware for osu! players. Exploring the limits of low-latency audio. 的本地化字符串。
        /// </summary>
        internal static string Wizard_Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Wizard_Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to KeyASIO 的本地化字符串。
        /// </summary>
        internal static string Wizard_Welcome_Title {
            get {
                return ResourceManager.GetString("Wizard_Welcome_Title", resourceCulture);
            }
        }
    }
}
