//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyAsio.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyAsio.Lang.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Device 的本地化字符串。
        /// </summary>
        internal static string AudioDevice {
            get {
                return ResourceManager.GetString("AudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beatmap 的本地化字符串。
        /// </summary>
        internal static string Beatmap {
            get {
                return ResourceManager.GetString("Beatmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer 的本地化字符串。
        /// </summary>
        internal static string Buffer {
            get {
                return ResourceManager.GetString("Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Device 的本地化字符串。
        /// </summary>
        internal static string ClearDevice {
            get {
                return ResourceManager.GetString("ClearDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver Panel 的本地化字符串。
        /// </summary>
        internal static string DriverPanel {
            get {
                return ResourceManager.GetString("DriverPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Bindings 的本地化字符串。
        /// </summary>
        internal static string EditBindings {
            get {
                return ResourceManager.GetString("EditBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engine Status 的本地化字符串。
        /// </summary>
        internal static string EngineStatus {
            get {
                return ResourceManager.GetString("EngineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclusive 的本地化字符串。
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to settings 的本地化字符串。
        /// </summary>
        internal static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latency 的本地化字符串。
        /// </summary>
        internal static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No device selected.  的本地化字符串。
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Time 的本地化字符串。
        /// </summary>
        internal static string PlayTime {
            get {
                return ResourceManager.GetString("PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Bindings 的本地化字符串。
        /// </summary>
        internal static string QuickBindings {
            get {
                return ResourceManager.GetString("QuickBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Device 的本地化字符串。
        /// </summary>
        internal static string ReloadDevice {
            get {
                return ResourceManager.GetString("ReloadDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample Rate 的本地化字符串。
        /// </summary>
        internal static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Status 的本地化字符串。
        /// </summary>
        internal static string SyncStatus {
            get {
                return ResourceManager.GetString("SyncStatus", resourceCulture);
            }
        }
    }
}
