<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>

    <Product>KeyASIO</Product>
    <Authors>Milkitic</Authors>
    <Company>Milkitic</Company>
    <Copyright>Copyright © Milkitic 2022~2026</Copyright>

    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Assets\KeyAsio.ico</ApplicationIcon>
    <AssemblyName>KeyASIO</AssemblyName>
    <AssemblyTitle>KeyASIO Audio Backend</AssemblyTitle>
    <PackageProjectUrl>https://github.com/Milkitic/KeyASIO.Net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Milkitic/KeyASIO.Net</RepositoryUrl>
    <Description>Exploring the limits of low-latency audio. An ASIO middleware optimization tool for rhythm gamers.</Description>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <RdXmlFile Include="rd.xml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NativeMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="NativeMethods.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\KeyAsio.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antelcat.I18N.SourceGenerators" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <!--Condition below can be used to remove AvaloniaUI.DiagnosticsSupport from build output in Release configuration.-->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <!--<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>-->
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NLog.Extensions.Logging" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="Semver" />
    <PackageReference Include="Sentry.Extensions.Logging" />
    <PackageReference Include="SmoothScroll.Avalonia" />
    <PackageReference Include="SukiUI" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\KeyAsio.Application\KeyAsio.Application.csproj" />
    <ProjectReference Include="..\..\Common\KeyAsio.Common\KeyAsio.Common.csproj" />
    <ProjectReference Include="..\..\Common\KeyAsio.Configuration\KeyAsio.Configuration.csproj" />
    <ProjectReference Include="..\..\Common\KeyAsio.Plugins.Contracts\KeyAsio.Plugins.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\KeyAsio.Secrets\KeyAsio.Secrets.csproj" />
    <ProjectReference Include="..\..\Core\KeyAsio.Core.Audio\KeyAsio.Core.Audio.csproj" />
    <ProjectReference Include="..\..\Core\KeyAsio.Sync\KeyAsio.Sync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Lang\SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Lang\SR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="CompatibleRun.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Create-Shortcut.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Import Project="Satori.targets" Condition="'$(RuntimeIdentifier)' == 'win-x64'" />

  <Target Name="SignOutput" AfterTargets="PostBuildEvent" Condition="Exists('$(MSBuildProjectDirectory)\keyasio_private.key')">
    <Message Text="Signing the output assembly to $(MSBuildProjectDirectory)..." Importance="High" />
    <Exec Command="pwsh -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\..\..\Signer.ps1&quot; sign &quot;$(TargetPath)&quot; &quot;$(MSBuildProjectDirectory)\keyasio_private.key&quot;" />
  </Target>

  <Target Name="SignPublishOutput" AfterTargets="Publish" Condition="Exists('$(MSBuildProjectDirectory)\keyasio_private.key')">
    <Message Text="Signing the published output assembly to $(PublishDir)..." Importance="High" />
    <Exec Command="pwsh -ExecutionPolicy Bypass -File &quot;$(MSBuildProjectDirectory)\..\..\Signer.ps1&quot; sign &quot;$(PublishDir)$(TargetFileName)&quot; &quot;$(MSBuildProjectDirectory)\keyasio_private.key&quot;" />
  </Target>
</Project>
