<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blake3" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="NAudio.Core" />
    <PackageReference Include="NAudio.Lame" />
    <PackageReference Include="NAudio.Vorbis" />
    <PackageReference Include="NAudio.Wasapi" />
    <PackageReference Include="NAudio.WinMM" />
    <PackageReference Include="System.Numerics.Tensors" />
    <PackageReference Include="z440.atl.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\dependencies\Milki.Extensions\src\Milki.Extensions.Threading\Milki.Extensions.Threading.csproj" />
    <ProjectReference Include="..\..\..\dependencies\NAudio\NAudio.Asio\NAudio.Asio.csproj" />
  </ItemGroup>

</Project>
