<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Coosu.Beatmap" />
    <PackageReference Include="dnlib" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\dependencies\osu.Game.Rulesets.OverlayAPI\OverlayAPI.LazerProtocol\OverlayAPI.LazerProtocol.csproj" />
    <ProjectReference Include="..\KeyAsio.Common\KeyAsio.Common.csproj" />
    <ProjectReference Include="..\KeyAsio.Configuration\KeyAsio.Configuration.csproj" />
    <ProjectReference Include="..\KeyAsio.Plugins.Contracts\KeyAsio.Plugins.Contracts.csproj" />
    <ProjectReference Include="..\..\Core\KeyAsio.Core.Audio\KeyAsio.Core.Audio.csproj" />
    <ProjectReference Include="..\..\Core\KeyAsio.Core.OsuAudio\KeyAsio.Core.OsuAudio.csproj" />
    <ProjectReference Include="..\..\Core\KeyAsio.Sync\KeyAsio.Sync.csproj" />
  </ItemGroup>

</Project>
